### ISSUE TITLE
Non-panicking variation

### ISSUE THREAD

**Issue by Diggsey** [davidpdrsn/assert-json-diff#10]
I would have liked to use this as part of a build script, but I didn't want to panic if there's a difference. It would be helpful to expose the comparison functions themselves.

**Comment by davidpdrsn** [comment]
What level of detail/control do you need? There already is [a function that performs the diff](https://github.com/davidpdrsn/assert-json-diff/blob/master/src/lib.rs#L236) and returns a `Result<(), String>` where the error is what will be passed to `panic!`. Is this fine or do you need more low access to the actual differences?

I would like to keep this crate focused on test assertions and don't want to expand into a full blown JSON diffing library, however I don't mind making `assert_json_no_panic` public.

**Comment by Diggsey** [comment]
Yeah just the message is fine: I just want to be able to report the error via a different channel than panicking.

**Comment by davidpdrsn** [comment]
Alright cool. I'll put some more thought into what exactly `assert_json_no_panic` should look like and then I'll make it public and stable.

**Comment by davidpdrsn** [comment]
The PR is now shipped in version 1.0.3
