### ISSUE TITLE
Breakage in 1.0.1 need no_panic API

### ISSUE THREAD

**Issue by vldm** [davidpdrsn/assert-json-diff#11]
Hi, in version 1.0.1 you broke `assert_json_no_panic` method.

I understand that this method was hidden from document, but this method is probably needed by some users https://github.com/lipanski/mockito/blob/master/src/lib.rs#L680

Can you please stabilize this method in some form.

**Comment by davidpdrsn** [comment]
Yes I will be stabilising the method as part of https://github.com/davidpdrsn/assert-json-diff/issues/10.

I do still consider the new release (1.0.2) non-breaking however since the `assert_json_no_panic` was hidden from the docs.
