### ISSUE TITLE
Breaking change between 1.0.2 and 1.0.3

### ISSUE THREAD

**Issue by luke-biel** [davidpdrsn/assert-json-diff#13]
function `assert_json_no_panic` and `Mode` were made private, which breaks `mockito` library

log:
```
   Compiling mockito v0.23.2
error[E0603]: function `assert_json_no_panic` is private
   --> /Users/lbi/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.23.2/src/lib.rs:565:24
    |
565 | use assert_json_diff::{assert_json_no_panic, Mode};
    |                        ^^^^^^^^^^^^^^^^^^^^

error[E0603]: enum `Mode` is private
   --> /Users/lbi/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.23.2/src/lib.rs:565:46
    |
565 | use assert_json_diff::{assert_json_no_panic, Mode};
    |                                              ^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0603`.
error: could not compile `mockito`.
```

Steps to reproduce:
* create new crate
* add `mockito = "0.23.2"` to dependencies
* build fails
* add `assert-json-diff = "=1.0.2"`
* build succeeds

This should be 2.0 release due to that

**Comment by davidpdrsn** [comment]
Sorry about this. However I don't consider the version breaking since `Mode` was hidden from the documentation. Instead you should use `assert_json_eq_no_panic` or `assert_json_include_no_panic` which we made stable in 1.0.3.

**Comment by luke-biel** [comment]
Problem is I'm not a developer of `mockito`. I have to wait for them to update their crate or add locked dependency to `assert-json-diff = "=1.0.2"` to all my crates which used up until now only `mockito`.
Any change in api should be bump in major version. I don't think it's matter of opinion. There's no way to know if other libs didn't break due to change.

You could keep `assert_json_no_panic` but deprecate it for now, until you are fine with `2.0` release.

**Comment by davidpdrsn** [comment]
The functionality they used weren't part of the public API because it wasn't in the docs. So changes to that aren't breaking IMO. Really they shouldn't have been using it in the first place.

I think you'll have to lock the version and wait until they update. I get this is unfortunate but at least it does mitigate the issue.

I will try to submit a PR to mockito today that fixes it. Hopefully they'll make a release quickly.

**Comment by luke-biel** [comment]
Well, anything not explicitly forbidden may be done :)

Thanks

**Comment by lipanski** [comment]
@davidpdrsn @luke-biel I opened a PR https://github.com/lipanski/mockito/pull/110 to fix this issue. please have a look.

**Comment by davidpdrsn** [comment]
Thanks a lot! Looks perfect 👌

**Comment by lipanski** [comment]
guess we can close this one, thanks for your help @davidpdrsn
