### ISSUE TITLE
Converting T to serde_json::Value?

### ISSUE THREAD

**Issue by leeola** [davidpdrsn/assert-json-diff#14]
Would it be problematic to allow the assert macros to automatically serialize values to a `serde_json::Value`? Something like:

```
pub fn diff<'a, Lhs, Rhs>(lhs: &'a Lhs, rhs: &'a Rhs, mode: Mode) -> Vec<Difference<'a>>
where
  Lhs: Serialize,
  Rhs: Serialize,
{
  let lhs = serde_json::to_value(lhs);
  let rhs = serde_json::to_value(rhs);
  // ...
}
```

_(ignore the lifetime for my example, hah)_

My use case is that my `actual` _(specifically)_  is usually an unserialized json type and my tests are cluttered with things like:

```
let resp: Json<Foo> = req().unwrap();
let resp = serde_json::to_value(resp.into_inner()).unwrap();
assert_json_eq!(resp, json!("foo"));
```

Not a big deal, just wondering if it has a downside. If there's no downside it seems like a nice improvement to accept more types which can naturally be serialized to `Value`. Thoughts?

**Comment by leeola** [comment]
On the same topic, it looks like the assert macros also have difficulty with refs:

```
            let a = json!({
                "a": { "b": 1 },
            });
            assert_json_include!(
                actual: &a,
                expected: &json!({
                    "a": {},
                })
            );
            assert_json_include!(
                actual: &a,
                expected: &json!({
                    "foo": {},
                })
            );
```

Something to deal with reuses of types would be beneficial too, unless I'm missing something :)

**Comment by davidpdrsn** [comment]
Good suggestion. Should be possible without breaking anything. I made a PR https://github.com/davidpdrsn/assert-json-diff/pull/15
