### ISSUE TITLE
Investigate serde_value

### ISSUE THREAD

**Issue by theduke** [davidpdrsn/assert-json-diff#16]
Hey, very useful crate, especially since https://github.com/colin-kiegel/rust-pretty-assertions can be problematic.

It might be a good idea to use https://github.com/arcnmx/serde-value instead of serde_json, because it is a much leaner dependency, and also has a more specific `Value` type.

**Comment by davidpdrsn** [comment]
Thanks for the suggestion but I think I'll be sticking with serde_json for now. I think the people who are likely to use this library are also likely to use serde_json.
