### ISSUE TITLE
NumericMode::AssumeFloat strictness

### ISSUE THREAD

**Issue by mooreniemi** [davidpdrsn/assert-json-diff#23]
I'm using `NumericMode::AssumeFloat` in `assert_json_diff::assert_json_matches` as described in https://docs.rs/assert-json-diff/2.0.1/assert_json_diff/macro.assert_json_matches.html I've confirmed the documented example works as expected.

But given how floats might be serialized, the matcher is not easy to use in practice.

My example that fails:

```
#[test]
fn json_comparison() {
    let config = Config::new(CompareMode::Strict).numeric_mode(NumericMode::AssumeFloat);

    // both are f32
    let params = Params {
        field_name_2: 0.6,
        field_name_1: 0.2,
    };
    let actual_json = serde_json::to_value(&params).unwrap();

    let expected_json = json!({
        "field_name_2": 0.6,
        "field_name_1": 0.2,
    });

    // comparing Value to Value types
    assert_json_matches!(actual_json, expected_json, config);
}
```

With this difference:

```
json atoms at path ".field_name_1" are not equal:
    lhs:
        0.20000000298023224
    rhs:
        0.2

json atoms at path ".field_name_2" are not equal:
    lhs:
        0.6000000238418579
    rhs:
        0.6
```

Sure enough, if I `println!` my `actual_json` I can see:

```
{
  "field_name_1":0.20000000298023224,
  "field_name_2":0.6000000238418579
}
```

I can blame this on `serde_json` but wdyt? Can there be a `within_precision` option to handle this? Not sure what level to fix at.

Dependencies:

```
assert-json-diff = "2"
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }
```

**Comment by davidpdrsn** [comment]
It seems to be related to how serde_json treats `f32`s. If you change the types to be `f64` then it works:

```rust
#[test]
fn comparing_floats() {
    #[derive(Debug, Serialize)]
    struct Params {
        field_name_1: f64,
        field_name_2: f64,
    }

    let config = Config::new(CompareMode::Strict).numeric_mode(NumericMode::AssumeFloat);

    // both are f32
    let params = Params {
        field_name_2: 0.6,
        field_name_1: 0.2,
    };

    let actual_json = serde_json::to_value(&params).unwrap();

    let expected_json = json!({
        "field_name_2": 0.6,
        "field_name_1": 0.2,
    });

    // comparing Value to Value types
    assert_json_matches!(actual_json, expected_json, config);
}
```

I noticed because [`serde_json::Number`](https://docs.rs/serde_json/1.0.64/serde_json/struct.Number.html) doesn't have methods to convert into `f32` but only `f64`.

Not sure there is anything assert_json_diff can do about that unfortunately.
